; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:xiao_esp32s3_modbus]
platform = espressif32@^6.7.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_eol = LF
board_build.partitions = default_8MB.csv

build_flags =
    -D BUILD_ID=\"${UNIX_TIME}\"

build_src_filter =
    -<*>
    +<main.cpp>
    +<Cell.cpp>
    +<Config.cpp>
    +<DrainWaterHopper.cpp>
    +<LoadCells.cpp>
    +<ModbusOrders.cpp>
    +<Utils.cpp>
    +<Valve.cpp>
    +<WaterInletHopper.cpp>
    -<main_old.cpp>
    -<main2.cpp>

lib_deps =
    HX711_ADC
    emelianov/modbus-esp8266
    Preferences
    https://github.com/Seeed-Studio/Grove_I2C_Motor_Driver_v1_3
